### PR TITLE
Fix sleep argument out of range error

### PR DESCRIPTION
**Pull request by rinigus**
Fixes

```
sleep: number 100000d is not in 0..4294967295 range
```

### CODE REVIEW

**Comment by neochapay** [comment]
I think 10d is few. Why not 40000 days ? It fits in range.
I ask because in my phone uptime over month

**Comment by rinigus** [comment]
It's a while loop with true in it. As such, any long duration will be fine. I selected 10d just with the view that it is long enough to have no impact on battery. If you wish, we can up that further.

**Comment by neochapay** [comment]
365d will be better as i think...

**Comment by rinigus** [comment]
OK, will change

**Comment by rinigus** [comment]
Bumped it to 365 days

**Pull request merged**
